### ISSUE TITLE
ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by Dhoot** [skb1129/fastapi-boilerplate#1]
when I am running 
`>alembic revision --autogenerate -m "train_stations"`

I am getting below error

```

(venv) D:\Codes\fastapi-trains>alembic revision --autogenerate -m "train_stations"
Traceback (most recent call last):
  File "C:\Users\rdhoo\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rdhoo\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Codes\fastapi-trains\venv\Scripts\alembic.exe\__main__.py", line 7, in <module>
  File "d:\codes\fastapi-trains\venv\lib\site-packages\alembic\config.py", line 559, in main
    CommandLine(prog=prog).main(argv=argv)
  File "d:\codes\fastapi-trains\venv\lib\site-packages\alembic\config.py", line 553, in main
    self.run_cmd(cfg, options)
  File "d:\codes\fastapi-trains\venv\lib\site-packages\alembic\config.py", line 530, in run_cmd
    fn(
  File "d:\codes\fastapi-trains\venv\lib\site-packages\alembic\command.py", line 212, in revision
    script_directory.run_env()
  File "d:\codes\fastapi-trains\venv\lib\site-packages\alembic\script\base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "d:\codes\fastapi-trains\venv\lib\site-packages\alembic\util\pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "d:\codes\fastapi-trains\venv\lib\site-packages\alembic\util\compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "migrations\env.py", line 5, in <module>
    from app.core import settings
ModuleNotFoundError: No module named 'app'
```

@skb1129 could please help to where I am doing sorry I am newbee to python

**Comment by skb1129** [comment]
@Dhoot This seems like a problem with your virtual env setup.

**Comment by skb1129** [comment]
@Dhoot I used to have this problem from time to time, so all I did to fix this was to `export PYTHONPATH=.` environment variable or use it before the command itself like this:
```bash
PYTHONPATH=. alembic revision --autogenerate -m "train_stations"
```
Let me know if this solves your problem

**Comment by skb1129** [comment]
Closing this due to inactivity.
